### ISSUE TITLE
tregex issue

### ISSUE THREAD

**Issue by valeryweber** [stanfordnlp/python-stanford-corenlp#30]
Hi All
I m trying to use the tregex python interface and I m getting internal server error 500.
Is there a fix for that issue?
Many thanks
valery

>>> import stanfordnlp.server as corenlp
>>> c=corenlp.CoreNLPClient(annotators='tokenize ssplit pos lemma ner depparse'.split(), timeout=60000)
>>> c.tregrex("Here we are.","(NP[$VP]>S)|(NP[$VP]>S\\n)|(NP\\n[$VP]>S)|(NP\\n[$VP]>S\\n)")
Traceback (most recent call last):
  File "/home/vwe/libs/pyenv/pyenv/versions/3.6.4/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 317, in __regex
    r.raise_for_status()
  File "/home/vwe/libs/pyenv/pyenv/versions/3.6.4/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/tregex?pattern=%28NP%5B%24VP%5D%3ES%29%7C%28NP%5B%24VP%5D%3ES%5Cn%29%7C%28NP%5Cn%5B%24VP%5D%3ES%29%7C%28NP%5Cn%5B%24VP%5D%3ES%5Cn%29&filter=False&properties=%7B%27annotators%27%3A+%27tokenize%2Cssplit%2Cpos%2Clemma%2Cner%2Cdepparse%27%2C+%27inputFormat%27%3A+%27text%27%2C+%27outputFormat%27%3A+%27serialized%27%2C+%27serializer%27%3A+%27edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer%27%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vwe/libs/pyenv/pyenv/versions/3.6.4/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 270, in tregrex
    return self.__regex('/tregex', text, pattern, filter, annotators, properties)
  File "/home/vwe/libs/pyenv/pyenv/versions/3.6.4/lib/python3.6/site-packages/stanfordnlp/server/client.py", line 323, in __regex
    raise AnnotationException(r.text)
stanfordnlp.server.client.AnnotationException: java.lang.NullPointerException: null

**Comment by arunchaganty** [comment]
I think the problem is that you haven't include "parse" in your list of annotators which provides the required constituency tree annotations. I would recommend either trying that out or using the new `stanfordnlp` package: https://github.com/stanfordnlp/stanfordnlp

**Comment by valeryweber** [comment]
Many thanks
v
